cmake_minimum_required(VERSION 3.5)
project(gsl VERSION 2.6)

execute_process(COMMAND ./configure --prefix=${CMAKE_INSTALL_PREFIX} WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})
add_custom_command(OUTPUT "${CMAKE_CURRENT_SOURCE_DIR}/.libs/${CMAKE_SHARED_LIBRARY_PREFIX}gsl${CMAKE_SHARED_LIBRARY_SUFFIX}" "${CMAKE_CURRENT_SOURCE_DIR}/.libs/${CMAKE_STATIC_LIBRARY_PREFIX}gsl${CMAKE_STATIC_LIBRARY_SUFFIX}" COMMAND $(MAKE) WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" COMMENT "Building gsl ...")

add_custom_target(gsl ALL DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/.libs/${CMAKE_SHARED_LIBRARY_PREFIX}gsl${CMAKE_SHARED_LIBRARY_SUFFIX}" "${CMAKE_CURRENT_SOURCE_DIR}/.libs/${CMAKE_STATIC_LIBRARY_PREFIX}gsl${CMAKE_STATIC_LIBRARY_SUFFIX}")

add_custom_command(TARGET gsl POST_BUILD COMMAND mv gsl gsl_sym && cp -rL gsl_sym gsl WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})


install(DIRECTORY gsl DESTINATION include)
install(FILES .libs/${CMAKE_STATIC_LIBRARY_PREFIX}gsl${CMAKE_STATIC_LIBRARY_SUFFIX} DESTINATION lib)


